# Generated by Django 4.2.25 on 2025-10-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('program_admin', 'Programme Administrator'), ('lab_technician', 'Lab Technician'), ('it_support', 'IT Support'), ('manager', 'Manager / Director')], default='student', max_length=32),
        ),
    ]
