# Generated by Django 4.2.25 on 2025-10-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
