# Generated by Django 4.2.25 on 2025-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp_is_used_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
