# Generated by Django 4.2.25 on 2025-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='work_end_hour',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='work_start_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
