# Generated by Django 4.2.25 on 2025-10-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('campus', models.CharField(blank=True, max_length=120, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_service', 'In Service'), ('out_of_service', 'Out of Service')], default='available', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='labs.lab')),
            ],
            options={
                'unique_together': {('lab', 'hostname')},
            },
        ),
    ]
