# Generated by Django 4.2.25 on 2025-10-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='description',
            new_name='equipment_profile',
        ),
        migrations.AlterField(
            model_name='lab',
            name='campus',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
