# Generated by Django 4.2.25 on 2025-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_rename_description_lab_equipment_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='equipment_profile',
            field=models.CharField(choices=[('keyboard', 'Keyboard'), ('printer', 'Printer'), ('projector', 'Projector'), ('headset', 'Headset / Audio Device'), ('webcam', 'Webcam'), ('other', 'Other Equipment'), ('mouse', 'Mouse'), ('laptop', 'Laptop / Notebook'), ('monitor', 'Monitor / Display')], max_length=10),
        ),
    ]
