# Generated by Django 4.2.25 on 2025-10-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_equipmentprofilemodel_alter_lab_equipment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('keyboard', 'Keyboard'), ('printer', 'Printer'), ('projector', 'Projector'), ('headset', 'Headset / Audio Device'), ('webcam', 'Webcam'), ('other', 'Other Equipment'), ('mouse', 'Mouse'), ('laptop', 'Laptop / Notebook'), ('monitor', 'Monitor / Display')], max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EquipmentProfileModel',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='equipment_profile',
        ),
        migrations.AddField(
            model_name='lab',
            name='equipment_profile',
            field=models.ManyToManyField(blank=True, related_name='labs', to='labs.equipmentprofile'),
        ),
    ]
