# Generated by Django 4.2.25 on 2025-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_equipmentprofile_delete_equipmentprofilemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentprofile',
            name='key',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='equipment_profile',
        ),
        migrations.AddField(
            model_name='equipmentprofile',
            name='name',
            field=models.CharField(choices=[('keyboard', 'Keyboard'), ('printer', 'Printer'), ('projector', 'Projector'), ('headset', 'Headset / Audio Device'), ('webcam', 'Webcam'), ('other', 'Other Equipment'), ('mouse', 'Mouse'), ('laptop', 'Laptop / Notebook'), ('monitor', 'Monitor / Display')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='equipment_profiles',
            field=models.ManyToManyField(blank=True, help_text='Select all equipment available in this lab', related_name='labs', to='labs.equipmentprofile'),
        ),
    ]
