# Generated by Django 4.2.25 on 2025-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_remove_equipmentprofile_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcasset',
            name='asset_tag',
        ),
        migrations.AlterField(
            model_name='pcasset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
